### PR TITLE
Allow content to shrink in thinner viewports

### PR DESCRIPTION
**Pull request by jayschwa**

### CODE REVIEW

**Comment by gutworth** [comment]
What does the padding do?

**Comment by jayschwa** [comment]
It keeps a little space on the edges when the viewport is less than the max width.

**Comment by alex** [comment]
Merge conflict on this now.

**Comment by gutworth** [comment]
As of 2eb6cf9890bacb600f2988e940e5c8b3b433655e, we now set a viewport which should improve the mobile experience. I dislike the wrapping that happens when the main table is too thin. Thank you for the contribution, though.

**Pull request closed without merging**
